### ISSUE TITLE
MaxRetryError

### ISSUE THREAD

**Issue by ZeroMcMuffin** [docusign/docusign-python-client#23] opened 2018-11-28 14:57 UTC
My first attempt at hitting the sandbox API always generates the following error:

HTTPSConnectionPool(host='www.docusign_esign.net', port=443): Max retries exceeded with url: /restapi/v2/accounts/919570/envelopes (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x113b3f7f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

If I try again, the connection succeeds as does the subsequent API request.  Is this expected in the sandbox (maybe cold starting workers or something behind the scenes)?

**Comment by LarryKlugerDS** [comment] 2018-11-28 17:30
Somehow you're using the wrong url. The developer sandbox is `https://demo.docusign.net` not `www.docusign_esign.net` as is shown on your error message.

Check out how the Python SDK should be configured from either the [JWT](https://github.com/docusign/eg-01-python-jwt) or [Authorization Code Grant](https://github.com/docusign/eg-03-python-auth-code-grant) examples.

**Comment by ZeroMcMuffin** [comment] 2018-11-28 17:43
@LarryKlugerDS 

I'm using the exact configuration parameters in your example from the readme:

base_url = "https://demo.docusign.net/restapi"

That domain name is not originating from my code.  And, again, a subsequent request using the same configuration ALWAYS succeeds.  Any ideas?

**Comment by LarryKlugerDS** [comment] 2018-11-28 18:05
Unfortunately the readme code has not been double-checked for awhile. 

To debug the problem: 
As a known-good test, can you download and run either the JWT authentication or Authorization Code Grant authentication as a separate project on your workstation and test it? 

By doing so, we can then determine if the problem is in the Readme code example/your code or elsewhere. 

Thank you for your time on this,
Larry

**Comment by LarryKlugerDS** [comment] 2019-03-25 17:56
Hi,

Please advise if you are still having this issue. 

We'll close this issue in a week or so if we don't hear back.

Thanks,
Larry

**Closed** 2019-04-04 07:12 UTC
Labels: answered, question, ready to close

**Comment by deadbeef404** [comment] 2019-11-19 03:43
For future reference, the URL www.docusign_esign.net was hardcoded in the v1 release, but that domain doesn't seem to exist anymore. I'm going to upgrade my version of this library and I suspect that will fix the issue.
