### ISSUE TITLE
Calling EnvelopesApi.list_tabs generates an exception

### ISSUE THREAD

**Issue by enigmablack** [docusign/docusign-python-client#22] opened 2018-11-15 23:47 UTC
Calling list_tabs from the EnvelopesApi is generating the following error. When it gets the response from the API and trying to parse the data, it is passing the entire dataTabs object into self._deserialize instead of iterating through it

````
Traceback (most recent call last):
  File "docu.py", line 60, in <module>
    envelope_data = envelopes_api.list_tabs(account_Id,envelope_id,1)
  File "docusign-python-client-master\docusign_esign\apis\envelopes_api.py", line 6708, in list_tabs
    (data) = self.list_tabs_with_http_info(account_id, envelope_id, recipient_id, **kwargs)
  File "docusign-python-client-master\docusign_esign\apis\envelopes_api.py", line 6804, in list_tabs_with_http_info
    collection_formats=collection_formats)
  File "docusign-python-client-master\docusign_esign\api_client.py", line 389, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "docusign-python-client-master\docusign_esign\api_client.py", line 216, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "docusign-python-client-master\docusign_esign\api_client.py", line 298, in deserialize
    return self.__deserialize(data, response_type)
  File "docusign-python-client-master\docusign_esign\api_client.py", line 342, in __deserialize
    return self.__deserialize_model(data, klass)
  File "docusign-python-client-master\docusign_esign\api_client.py", line 696, in __deserialize_model
    setattr(instance, attr, self.__deserialize(value, attr_type))
  File "docusign-python-client-master\docusign_esign\api_client.py", line 319, in __deserialize
    for sub_data in data]
  File "docusign-python-client-master\docusign_esign\api_client.py", line 319, in <listcomp>
    for sub_data in data]
  File "docusign-python-client-master\docusign_esign\api_client.py", line 338, in __deserialize
    return self.__deserialize_date(data)
  File "docusign-python-client-master\docusign_esign\api_client.py", line 644, in __deserialize_date
    return parse(string).date()
  File "AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateutil\parser\_parser.py", line 1356, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateutil\parser\_parser.py", line 645, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateutil\parser\_parser.py", line 721, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateutil\parser\_parser.py", line 207, in split
    return list(cls(s))
  File "AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateutil\parser\_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not dict
````

**Comment by Cookiehook** [comment] 2019-02-09 20:24
I've found the cause and solution for this. *Disclaimer* I'm not a Docusign developer, I found this whilst investigating the same issue for another client.
Specifically, this occurs when trying to deserialise text fields that have been restricted to dates, which are returned from the API as date_tabs objects.

The deserialisation process uses a dictionary of swagger_types in the appropriate parent object to determine what Python object the child JSON object (from the API call) will return.
The Tabs class has the following entry for date_tabs:
- 'date_tabs': 'list[date]',
When processed by the api_client.__deserialize method, the klass string gets converted to the primitive 'date' type, and passes the JSON object into api_client.__deserialize_date

It should read:
- 'date_tabs': 'list[Date]',
Note the capital D. This isn't treated as a primitive date, so enters the api_client.__deserialize_model method, and correctly selects the docusign Date object. Changing that capitalisation fixes the problem in my test environment, so date_tabs are properly handled, and no exception is raised.
From the documentation, it seems that this code is autogenerated from the swagger framework, so the change will need to be made there and re-generated.

NB: The same problem also exists in template_tabs, though those objects aren't in my use-case, so I haven't tested it.


Line in Tabs class: https://github.com/docusign/docusign-python-client/blob/ce27345496da4b6e78a78e6dd3f6e1835d4a5e31/docusign_esign/models/tabs.py#L38

**Comment by LarryKlugerDS** [comment] 2019-02-10 19:42
@enigmablack -- thank you for reporting the problem.

@Cookiehook -- thank you for the confirmation and proposed fix.

I have submitted internal bug report # DCM-3102 and forwarded to our engineering group. Since the SDK is mechanically produced via the Swagger file and its CodeGen app, engineering may need to update the CodeGen app to generate a fix.

This issue will remain open until a fix version is published.

**Comment by LarryKlugerDS** [comment] 2019-02-10 19:45
To help increase the prioritization of the bug report, please ask your DocuSign business or technical contact to add your organization's information to the DCM-3102 ticket. Thank you.

**Comment by LarryKlugerDS** [comment] 2019-03-26 10:56
Potential work-around: use EnvelopeFormData::get to list the values for all of the tabs.

See https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeFormData/get

**Comment by LarryKlugerDS** [comment] 2019-03-26 11:42
I have created a test case for this bug from the eg-03-python-auth-code-grant example. 
See https://github.com/docusign/eg-03-python-auth-code-grant/tree/issue-22_larryk

I have also tried the test case with the alpha version of the forthcoming Python SDK version. Unfortunately the test case still does not work.

The Engineering group will determine if the problem is in the SDK or in the Swagger file specification.

**Comment by ellapetkova** [comment] 2019-04-02 14:42
@LarryKlugerDS 

> 
> 
> Potential work-around: use EnvelopeFormData::get to list the values for all of the tabs.
> 
> See https://developers.docusign.com/esign-rest-api/reference/Envelopes/EnvelopeFormData/get

Have successfully used this call to get data required, but will continue watching this issue for progress updates.

**Comment by LarryKlugerDS** [comment] 2019-04-02 19:41
Thank you @ellapetkova  for the update.

**Comment by LarryKlugerDS** [comment] 2019-09-02 11:31
Good news, DCM-3102 is in active development.

**Comment by LarryKlugerDS** [comment] 2020-01-02 17:00
I believe this bug has been fixed in the current version. Please check. I am also checking the release version with the DocuSign engineering group.

**Comment by LarryKlugerDS** [comment] 2020-04-06 10:34
No reply. Assuming that the fix is correct. Closing

**Closed by LarryKlugerDS** 2020-04-06 10:34 UTC
Labels: DCM-3102, bug, test case
